### ISSUE TITLE
Fatal error in Linux

### ISSUE THREAD

**Issue by jesusjmma** [algono/clips-ide-vscode#2]
Cuando quieres abrir el entorno de CLIPS sale un error fatal indicando que no está CLIPS instalado.

**Comment by algono** [comment]
Hola, en Linux la extensión asume por defecto que CLIPS está instalado y disponible ejecutando el comando `clips` en el terminal.

Si el archivo se llama de otra forma o no está disponible en el `PATH`, le puedes indicar la ruta en las preferencias (`clips.clipsPath`).

La extensión no instala CLIPS automáticamente, hay que instalarlo manualmente. CLIPS no tiene un instalador para Linux, así que hay que compilarlo con el código fuente (aunque por ejemplo para Arch hay un paquete en la AUR que instala la versión 6.31).

Espero que esto te sirva para resolver el problema. Si no, no dudes en comentarlo.
